-- ============================================================
-- TORO MOVERS CRM v2 — Storage: Quotes bucket
-- ============================================================
-- Run AFTER 001_init.sql. Safe to re-run.
--
-- Creates a private 'quotes' storage bucket. All reads happen via
-- signed URLs generated by the quote-pdf / quote-send Netlify
-- functions using the service role key (which bypasses RLS).
--
-- No client-side access to storage.objects is granted — every
-- download flows through a short-lived signed URL.
-- ============================================================

insert into storage.buckets (id, name, public)
values ('quotes', 'quotes', false)
on conflict (id) do nothing;

-- Explicitly: no policy on storage.objects for the 'quotes' bucket.
-- Supabase RLS default-denies, so authenticated clients cannot
-- list / read / write objects directly. Service role bypasses RLS,
-- so the server-side functions can upload + sign.
--
-- If we later need in-dashboard browsing via the Supabase UI, note
-- that the dashboard uses the service role and will still work.
